name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - test

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: printenv
    - name: post a message to slack
      uses: ./
      env:
        INCOMING_WEBHOOK_URL: TEST_WEBHOOK_URL
      with:
        text: slack-incoming-webhook sample